/** Public URLs for built-in site pictures (synced into public/cms-uploads/site/). */
export const siteMedia = {
  logo: "/cms-uploads/site/orderweb-logo.png",
  favicon: "/cms-uploads/site/favicon.png",
  homeHero: "/cms-uploads/site/home-hero-desktop.jpg",
  homeHeroMobile: "/cms-uploads/site/home-hero-mobile.jpg",
  whyOrderWeb: "/cms-uploads/site/why-orderweb-visual.jpg",
  aboutFloorStory: "/cms-uploads/site/about-floor-story.png",
  pricingCommission: "/cms-uploads/site/pricing-commission-scale.png",
  contactLondon: "/cms-uploads/site/contact-london-hero.png",
  posHardware: "/cms-uploads/site/pos-hardware-hero.png",
  posDashboard: "/cms-uploads/site/pos-screen-dashboard.png",
  posStoreOps: "/cms-uploads/site/pos-screen-store-ops.png",
  posBusinessAdmin: "/cms-uploads/site/pos-screen-business-admin.png",
  posStaffCustomers: "/cms-uploads/site/pos-screen-staff-customers.png",
  websiteDevices: "/cms-uploads/site/website-devices-hero.png",
  demoRestaurant1: "/cms-uploads/site/demo-restaurant-1.png",
  demoRestaurant2: "/cms-uploads/site/demo-restaurant-2.png",
  demoRestaurant3: "/cms-uploads/site/demo-restaurant-3.png",
  demoRetail1: "/cms-uploads/site/demo-retail-1.png",
  demoRetail2: "/cms-uploads/site/demo-retail-2.png",
  demoRetail3: "/cms-uploads/site/demo-retail-3.png",
  demoServices1: "/cms-uploads/site/demo-services-1.png",
  demoServices2: "/cms-uploads/site/demo-services-2.png",
  demoServices3: "/cms-uploads/site/demo-services-3.png",
  softwarePhone: "/cms-uploads/site/software-phone-hero.png",
} as const;
