/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CustomWebsiteRouteImport } from './routes/custom-website'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OwadminRouteRouteImport } from './routes/owadmin/route'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RestaurantPosRouteImport } from './routes/restaurant-pos'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as OwadminIndexRouteImport } from './routes/owadmin/index'
import { Route as OwadminAccountRouteImport } from './routes/owadmin/account'
import { Route as OwadminActivityRouteImport } from './routes/owadmin/activity'
import { Route as OwadminMediaRouteImport } from './routes/owadmin/media'
import { Route as OwadminResetPasswordRouteImport } from './routes/owadmin/reset-password'
import { Route as OwadminSettingsRouteImport } from './routes/owadmin/settings'
import { Route as OwadminSocialRouteImport } from './routes/owadmin/social'
import { Route as OwadminUsersRouteImport } from './routes/owadmin/users'
import { Route as OwadminPagesPageKeyRouteImport } from './routes/owadmin/pages.$pageKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomWebsiteRoute = CustomWebsiteRouteImport.update({
  id: '/custom-website',
  path: '/custom-website',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OwadminRouteRoute = OwadminRouteRouteImport.update({
  id: '/owadmin',
  path: '/owadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantPosRoute = RestaurantPosRouteImport.update({
  id: '/restaurant-pos',
  path: '/restaurant-pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const OwadminIndexRoute = OwadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwadminRouteRoute,
} as any)
const OwadminAccountRoute = OwadminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => OwadminRouteRoute,
} as any)
const OwadminActivityRoute = OwadminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => OwadminRouteRoute,
} as any)
const OwadminMediaRoute = OwadminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => OwadminRouteRoute,
} as any)
const OwadminResetPasswordRoute = OwadminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => OwadminRouteRoute,
} as any)
const OwadminSettingsRoute = OwadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwadminRouteRoute,
} as any)
const OwadminSocialRoute = OwadminSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => OwadminRouteRoute,
} as any)
const OwadminUsersRoute = OwadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OwadminRouteRoute,
} as any)
const OwadminPagesPageKeyRoute = OwadminPagesPageKeyRouteImport.update({
  id: '/pages/$pageKey',
  path: '/pages/$pageKey',
  getParentRoute: () => OwadminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owadmin': typeof OwadminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/custom-website': typeof CustomWebsiteRoute
  '/dpa': typeof DpaRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/restaurant-pos': typeof RestaurantPosRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software': typeof SoftwareRoute
  '/terms': typeof TermsRoute
  '/website': typeof WebsiteRoute
  '/owadmin/account': typeof OwadminAccountRoute
  '/owadmin/activity': typeof OwadminActivityRoute
  '/owadmin/media': typeof OwadminMediaRoute
  '/owadmin/reset-password': typeof OwadminResetPasswordRoute
  '/owadmin/settings': typeof OwadminSettingsRoute
  '/owadmin/social': typeof OwadminSocialRoute
  '/owadmin/users': typeof OwadminUsersRoute
  '/owadmin/': typeof OwadminIndexRoute
  '/owadmin/pages/$pageKey': typeof OwadminPagesPageKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/custom-website': typeof CustomWebsiteRoute
  '/dpa': typeof DpaRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/restaurant-pos': typeof RestaurantPosRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software': typeof SoftwareRoute
  '/terms': typeof TermsRoute
  '/website': typeof WebsiteRoute
  '/owadmin/account': typeof OwadminAccountRoute
  '/owadmin/activity': typeof OwadminActivityRoute
  '/owadmin/media': typeof OwadminMediaRoute
  '/owadmin/reset-password': typeof OwadminResetPasswordRoute
  '/owadmin/settings': typeof OwadminSettingsRoute
  '/owadmin/social': typeof OwadminSocialRoute
  '/owadmin/users': typeof OwadminUsersRoute
  '/owadmin': typeof OwadminIndexRoute
  '/owadmin/pages/$pageKey': typeof OwadminPagesPageKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owadmin': typeof OwadminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/custom-website': typeof CustomWebsiteRoute
  '/dpa': typeof DpaRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/restaurant-pos': typeof RestaurantPosRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software': typeof SoftwareRoute
  '/terms': typeof TermsRoute
  '/website': typeof WebsiteRoute
  '/owadmin/account': typeof OwadminAccountRoute
  '/owadmin/activity': typeof OwadminActivityRoute
  '/owadmin/media': typeof OwadminMediaRoute
  '/owadmin/reset-password': typeof OwadminResetPasswordRoute
  '/owadmin/settings': typeof OwadminSettingsRoute
  '/owadmin/social': typeof OwadminSocialRoute
  '/owadmin/users': typeof OwadminUsersRoute
  '/owadmin/': typeof OwadminIndexRoute
  '/owadmin/pages/$pageKey': typeof OwadminPagesPageKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owadmin'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/custom-website'
    | '/dpa'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/restaurant-pos'
    | '/services'
    | '/sitemap.xml'
    | '/software'
    | '/terms'
    | '/website'
    | '/owadmin/account'
    | '/owadmin/activity'
    | '/owadmin/media'
    | '/owadmin/reset-password'
    | '/owadmin/settings'
    | '/owadmin/social'
    | '/owadmin/users'
    | '/owadmin/'
    | '/owadmin/pages/$pageKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/custom-website'
    | '/dpa'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/restaurant-pos'
    | '/services'
    | '/sitemap.xml'
    | '/software'
    | '/terms'
    | '/website'
    | '/owadmin/account'
    | '/owadmin/activity'
    | '/owadmin/media'
    | '/owadmin/reset-password'
    | '/owadmin/settings'
    | '/owadmin/social'
    | '/owadmin/users'
    | '/owadmin'
    | '/owadmin/pages/$pageKey'
  id:
    | '__root__'
    | '/'
    | '/owadmin'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/custom-website'
    | '/dpa'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/restaurant-pos'
    | '/services'
    | '/sitemap.xml'
    | '/software'
    | '/terms'
    | '/website'
    | '/owadmin/account'
    | '/owadmin/activity'
    | '/owadmin/media'
    | '/owadmin/reset-password'
    | '/owadmin/settings'
    | '/owadmin/social'
    | '/owadmin/users'
    | '/owadmin/'
    | '/owadmin/pages/$pageKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwadminRouteRoute: typeof OwadminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CustomWebsiteRoute: typeof CustomWebsiteRoute
  DpaRoute: typeof DpaRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RestaurantPosRoute: typeof RestaurantPosRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoftwareRoute: typeof SoftwareRoute
  TermsRoute: typeof TermsRoute
  WebsiteRoute: typeof WebsiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-website': {
      id: '/custom-website'
      path: '/custom-website'
      fullPath: '/custom-website'
      preLoaderRoute: typeof CustomWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owadmin': {
      id: '/owadmin'
      path: '/owadmin'
      fullPath: '/owadmin'
      preLoaderRoute: typeof OwadminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant-pos': {
      id: '/restaurant-pos'
      path: '/restaurant-pos'
      fullPath: '/restaurant-pos'
      preLoaderRoute: typeof RestaurantPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owadmin/': {
      id: '/owadmin/'
      path: '/'
      fullPath: '/owadmin/'
      preLoaderRoute: typeof OwadminIndexRouteImport
      parentRoute: typeof OwadminRouteRoute
    }
    '/owadmin/account': {
      id: '/owadmin/account'
      path: '/account'
      fullPath: '/owadmin/account'
      preLoaderRoute: typeof OwadminAccountRouteImport
      parentRoute: typeof OwadminRouteRoute
    }
    '/owadmin/activity': {
      id: '/owadmin/activity'
      path: '/activity'
      fullPath: '/owadmin/activity'
      preLoaderRoute: typeof OwadminActivityRouteImport
      parentRoute: typeof OwadminRouteRoute
    }
    '/owadmin/media': {
      id: '/owadmin/media'
      path: '/media'
      fullPath: '/owadmin/media'
      preLoaderRoute: typeof OwadminMediaRouteImport
      parentRoute: typeof OwadminRouteRoute
    }
    '/owadmin/reset-password': {
      id: '/owadmin/reset-password'
      path: '/reset-password'
      fullPath: '/owadmin/reset-password'
      preLoaderRoute: typeof OwadminResetPasswordRouteImport
      parentRoute: typeof OwadminRouteRoute
    }
    '/owadmin/settings': {
      id: '/owadmin/settings'
      path: '/settings'
      fullPath: '/owadmin/settings'
      preLoaderRoute: typeof OwadminSettingsRouteImport
      parentRoute: typeof OwadminRouteRoute
    }
    '/owadmin/social': {
      id: '/owadmin/social'
      path: '/social'
      fullPath: '/owadmin/social'
      preLoaderRoute: typeof OwadminSocialRouteImport
      parentRoute: typeof OwadminRouteRoute
    }
    '/owadmin/users': {
      id: '/owadmin/users'
      path: '/users'
      fullPath: '/owadmin/users'
      preLoaderRoute: typeof OwadminUsersRouteImport
      parentRoute: typeof OwadminRouteRoute
    }
    '/owadmin/pages/$pageKey': {
      id: '/owadmin/pages/$pageKey'
      path: '/pages/$pageKey'
      fullPath: '/owadmin/pages/$pageKey'
      preLoaderRoute: typeof OwadminPagesPageKeyRouteImport
      parentRoute: typeof OwadminRouteRoute
    }
  }
}

interface OwadminRouteRouteChildren {
  OwadminAccountRoute: typeof OwadminAccountRoute
  OwadminActivityRoute: typeof OwadminActivityRoute
  OwadminMediaRoute: typeof OwadminMediaRoute
  OwadminResetPasswordRoute: typeof OwadminResetPasswordRoute
  OwadminSettingsRoute: typeof OwadminSettingsRoute
  OwadminSocialRoute: typeof OwadminSocialRoute
  OwadminUsersRoute: typeof OwadminUsersRoute
  OwadminIndexRoute: typeof OwadminIndexRoute
  OwadminPagesPageKeyRoute: typeof OwadminPagesPageKeyRoute
}

const OwadminRouteRouteChildren: OwadminRouteRouteChildren = {
  OwadminAccountRoute: OwadminAccountRoute,
  OwadminActivityRoute: OwadminActivityRoute,
  OwadminMediaRoute: OwadminMediaRoute,
  OwadminResetPasswordRoute: OwadminResetPasswordRoute,
  OwadminSettingsRoute: OwadminSettingsRoute,
  OwadminSocialRoute: OwadminSocialRoute,
  OwadminUsersRoute: OwadminUsersRoute,
  OwadminIndexRoute: OwadminIndexRoute,
  OwadminPagesPageKeyRoute: OwadminPagesPageKeyRoute,
}

const OwadminRouteRouteWithChildren = OwadminRouteRoute._addFileChildren(
  OwadminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwadminRouteRoute: OwadminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CustomWebsiteRoute: CustomWebsiteRoute,
  DpaRoute: DpaRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RestaurantPosRoute: RestaurantPosRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoftwareRoute: SoftwareRoute,
  TermsRoute: TermsRoute,
  WebsiteRoute: WebsiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
